listen              1935;
http_server {
    enabled         on;
    listen          8080;
}

vhost live {
    cluster {
        mode edge;
        origin srs_origin:1935; # Local dev, deploy production đổi thành domain
    }
}
