listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;
srs_log_level       info;

http_api {
    enabled         on;
    listen          1985;
}

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

rtc_server {
    enabled         on;
    listen          8000;
    candidate       0.0.0.0;
    iceport_min 10000;
    iceport_max 20000;
}

vhost live {
    rtc {
        enabled     on;
        rtmp_to_rtc on;
        rtc_to_rtmp on;
        min_latency on;
    }

    dvr {
        enabled on;
        dvr_apply all;
        dvr_path /usr/local/srs/records/[stream].mp4;
        dvr_plan session;
    }

    http_hooks {
        enabled on;
        on_publish http://host.docker.internal:3000/api/live/on-publish;
        on_unpublish http://host.docker.internal:3000/api/live/on-stop;
    }
}
