import React from 'react'
import { VideoPreviewCard } from '../components/common/VideoPreviewCard/VideoPreviewCard'

export default function UserHome() {
  return (
    <>
      <VideoPreviewCard videoId="vXoXmV7CEyI" title="𝐏𝐥𝐚𝐲𝐥𝐢𝐬𝐭 Chỉ vô tình nghe thôi mà hợp vibe quá |🎧 Playlist hip-hop được chủ kênh tuyển chọn kỹ lưỡng" channel="Nabi và 𝐇𝐚𝐯𝐞𝐧" duration="41:15" publishedAt="8 ngày trước" views="80 N lượt xem" thumbnailUrl="https://i.ytimg.com/vi/cvdsst3LYws/hq720.jpg?sqp=-oaymwFBCNAFEJQDSFryq4qpAzMIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB8AEB-AH-CYAC0AWKAgwIABABGGUgVChLMA8=&rs=AOn4CLDO0my2mamZloYCpQsNRrkgwStnJg" previewUrl="https://youtu.be/cvdsst3LYws?list=RDcvdsst3LYws" avatar='https://yt3.ggpht.com/8OvO6JSUcP5YaxmKK5xJy71r79tKp58U14Rj34jG5CrE78-8sJjTlAzJe1EcKR5MySuf1MVK3s0=s88-c-k-c0x00ffffff-no-rj'/>
      <VideoPreviewCard videoId="vXoXmV7CEyII" title="【8D环绕】大马女孩Penny的《打火机》播放破10亿『吉隆坡的天氣它是翻雲又覆雨，灰濛濛的烏雲好幾天沒見到你』【動態歌詞/Lyrics Music】♪" channel="音樂安利站 Beats Music" duration="1:01:01" publishedAt="1 tháng trước" views="147 N lượt xem" thumbnailUrl="https://i.ytimg.com/vi/nyCORWy8UqE/hq720.jpg?sqp=-oaymwFBCNAFEJQDSFryq4qpAzMIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB8AEB-AH-CYAC0AWKAgwIABABGGUgXyhVMA8=&rs=AOn4CLCKGt1dC2NCYnO4hZQ4zc4p0k_oAg" previewUrl="https://youtu.be/nyCORWy8UqE?list=RDnyCORWy8UqE" avatar='https://yt3.ggpht.com/gZDyvGKgBEP-KBOq41TvW_MfW27TKP1yur8S3pBII-kU01cq3D_gtJXk_5BfTLmdySFIfu_VNQ=s48-c-k-c0x00ffffff-no-rj'/>
      <VideoPreviewCard videoId="vXoXmV7CEyIII" title="VALULRANT ỒN NHƯ VỠ CHỢ CÙNG.." channel="Dev Nguyen" duration="50:13" publishedAt="2 ngày trước" views="50 N lượt xem" thumbnailUrl="https://i.ytimg.com/vi/d1t5RmYRDrQ/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLD7eJvnuo_SB_ddcyaX_fI7498AnQ" previewUrl="https://youtu.be/d1t5RmYRDrQ" avatar='https://yt3.ggpht.com/LnhEUlBi01R5NVE0kptufPPpsFY-l70qwbEH-ENe3HPjgrx1M5kWnB0-oqwq9CDyhibZ3lJd=s48-c-k-c0x00ffffff-no-rj' />
      <VideoPreviewCard videoId="vXoXmV7CEyIV" title="co-streaming MAJOR CS2 | FAZE, NIP, ASTRALIS, NAVI, LIQUID..." channel="Bomman" views="2.103 N lượt xem" thumbnailUrl="https://i.ytimg.com/vi/Bh9RAnyTvK4/hq720.jpg?v=6929f10c&sqp=CMjSsskG-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBGvDKTkU9ixluu6Fe8id_yBaLYLQ" previewUrl="https://youtu.be/Bh9RAnyTvK4" avatar='https://yt3.ggpht.com/V8TIv129UM7pBcVXrwTv-QBwOwWPryuwe0OO8Mn8sp2ooXy2VJVGoPikI71uiIE0qLPUyyTLi7k=s48-c-k-c0x00ffffff-no-rj' isLive={true}/>
      <VideoPreviewCard videoId="vXoXmV7CEyV" title="| TÂM SỰ ĐÊM KHUYA | YÊU NHAU BỊ GIA ĐÌNH CẤM CẢN THÌ PHẢI LÀM SAO????" channel="PEWPEW" duration="1:28:27" publishedAt="1 tháng trước" views="89 N lượt xem" thumbnailUrl="https://i.ytimg.com/vi/ubhGxueHhwA/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLAzPaes57iBRj7Uyyy4kGXPihrDPA" previewUrl="https://youtu.be/ubhGxueHhwA"  avatar='https://yt3.ggpht.com/fK3ofGISQtYQUoQAx5_6PEKv7nJl-VUuCsC4LDw6uRCIva12WrEZguW06q65G8rAplALyX-oKg=s48-c-k-c0x00ffffff-no-rj'/>
      <VideoPreviewCard videoId="vXoXmV7CEyVI" title="2 Ngày 1 Đêm Mùa 4 | Tập 91: HIEUTHUHAI bị 'thảo khấu' chơi xấu, 'Hằng Nga' Đỗ Nhật Hoàng lộ diện" channel="ĐÔNG TÂY PROMOTION OFFICIAL" duration="2:08:30" publishedAt="7 giờ trước" views="454 N lượt xem" thumbnailUrl="https://i.ytimg.com/vi/4LI8wAn7yn4/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLApDzuCGRlTsvaBuyKY-5jcazHzrQ" previewUrl="https://youtu.be/4LI8wAn7yn4" avatar='https://yt3.ggpht.com/DuBXzDiu-fh09cGe34gjNWoPyjyyxG44eDo7NbzTni7f3RqbLZvr7p7RM1QldX4EJya5-wAdUw=s48-c-k-c0x00ffffff-no-rj' />
      <VideoPreviewCard videoId="vXoXmV7CEyVII" title="Lạc Vào Khu Rừng Hoa - Nắng Ấm Trong Tim - NHẠC REMIX TIKTOK TRIỆU VIEW, Top 20 Nhạc TikTok Hay 2025" channel="BD Media Music" duration="49:30" publishedAt="2 ngày trước" views="103 N lượt xem" thumbnailUrl="https://i.ytimg.com/vi/a4K_P5uqlrE/hqdefault.jpg?sqp=-oaymwEnCPYBEIoBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBtzaNewlRj0DsH72O2oTZYPTykPg" previewUrl="https://media.istockphoto.com/id/1160913968/vi/video/m%E1%BB%99t-%C4%91%C3%A1m-%C4%91%C3%B4ng-ng%C6%B0%E1%BB%9Di-bi%E1%BB%83u-t%C3%ACnh-%C4%91ang-k%C3%ADch-%C4%91%E1%BB%99ng-%C4%91%C3%ACnh-c%C3%B4ng-ch%E1%BB%91ng-l%E1%BA%A1i-ch%C3%ADnh-ph%E1%BB%A7.mp4?s=mp4-640x640-is&k=20&c=-PN1_NfN4lzDuj2wiK3WPobdmmayO1zf_4AcZH8VuUU=" />
      <VideoPreviewCard videoId="vXoXmV7CEyVIII" title="ALL IN ONE | Học Sinh Mạnh Nhất Trường Học Ma Pháp | Review Anime Ha" channel="Bo Kin Backup" duration="49:30" publishedAt="3 tháng trước" views="552 N lượt xem" thumbnailUrl="https://i.ytimg.com/vi/vXoXmV7CEyI/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBcyMR909QKOiCt9P0IOMeDnXIJUQ" previewUrl="https://cdn.pixabay.com/video/2016/10/21/6047-188286517_large.mp4" />
      <VideoPreviewCard videoId="vXoXmV7CEyIX" title="PUBG PC I AL_Himass #79 I Game đấu bùng nổ của Himass" channel="Pro Player VN" duration="49:30" publishedAt="1 tháng trước" views="31 N lượt xem" thumbnailUrl="https://i.ytimg.com/vi/r-GR_5DMIqU/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLD8joMnBaMhdQbfWH0KNs19CTYf3A" previewUrl="https://cdn.pixabay.com/video/2020/12/30/60721-499068724_large.mp4" isLive={true} />
    </>
  )
}
